"use client";

/**
 * /deposit/[token]
 *
 * Public page for renters to authorize a security deposit hold.
 * Token is generated by the operator via /api/payments/deposit/initiate.
 *
 * Flow:
 * 1. Fetch booking info using token (GET /api/payments/deposit?token=xxx)
 * 2. Create PaymentIntent (POST /api/payments/deposit with deposit_token)
 * 3. Show Stripe Elements (card entry)
 * 4. On submit: stripe.confirmPayment → authorization hold placed
 * 5. On success: POST /api/payments/deposit/capture with {token, payment_intent_id}
 *    to mark booking deposit_status = 'held'
 */

import { useEffect, useState, Suspense, use } from "react";
import { loadStripe } from "@stripe/stripe-js";
import {
  Elements,
  PaymentElement,
  useStripe,
  useElements,
} from "@stripe/react-stripe-js";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Lock,
  CheckCircle2,
  AlertCircle,
  ShieldCheck,
  Car,
  Calendar,
  DollarSign,
} from "lucide-react";

const stripePromise = loadStripe(
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!
);

interface BookingInfo {
  id: string;
  renter_name: string;
  start_date: string;
  end_date: string;
  duration_days: number;
  deposit_amount: number;
  deposit_status: string;
  vehicle: { make: string; model: string; year: number } | null;
  operator_name: string;
  stripe_connected: boolean;
  already_held?: boolean;
  completed?: boolean;
}

// ── Stripe checkout form ─────────────────────────────────────────────────────

function DepositForm({
  token,
  bookingInfo,
  paymentIntentId,
  onSuccess,
}: {
  token: string;
  bookingInfo: BookingInfo;
  paymentIntentId: string;
  onSuccess: () => void;
}) {
  const stripe = useStripe();
  const elements = useElements();
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!stripe || !elements) return;

    setProcessing(true);
    setError(null);

    const { error: submitError } = await elements.submit();
    if (submitError) {
      setError(submitError.message ?? "An error occurred");
      setProcessing(false);
      return;
    }

    const { error: confirmError, paymentIntent } = await stripe.confirmPayment({
      elements,
      confirmParams: {
        return_url: `${window.location.origin}/deposit/${token}?confirmed=1&pi=${paymentIntentId}`,
      },
      redirect: "if_required",
    });

    if (confirmError) {
      setError(confirmError.message ?? "Authorization failed. Please check your card details.");
      setProcessing(false);
      return;
    }

    // Notify server: mark booking as held
    try {
      const res = await fetch("/api/payments/deposit/capture", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, payment_intent_id: paymentIntent?.id ?? paymentIntentId }),
      });
      const data = await res.json();
      if (!res.ok) {
        console.error("Confirm hold error:", data.error);
        // Still show success if Stripe confirmed — server will catch up
      }
    } catch (err) {
      console.error("Confirm API call failed:", err);
    }

    onSuccess();
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <PaymentElement
        options={{
          layout: "tabs",
          fields: {
            billingDetails: "auto",
          },
        }}
      />
      {error && (
        <div className="flex items-start gap-2 rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-700">
          <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
          {error}
        </div>
      )}
      <div className="rounded-lg bg-blue-50 border border-blue-200 p-3 text-sm text-blue-700 flex items-start gap-2">
        <ShieldCheck className="h-4 w-4 mt-0.5 shrink-0" />
        <span>
          <strong>Authorization only</strong> — your card will not be charged unless there is damage, late fees, or other issues. 
          The hold will be released when you return the vehicle in good condition.
        </span>
      </div>
      <Button
        type="submit"
        className="w-full"
        disabled={processing || !stripe || !elements}
        style={{ backgroundColor: "#2EBD6B" }}
      >
        {processing ? (
          <span className="flex items-center gap-2">
            <span className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
            Authorizing…
          </span>
        ) : (
          <span className="flex items-center gap-2">
            <Lock className="h-4 w-4" />
            Authorize ${Number(bookingInfo.deposit_amount).toFixed(2)} Hold
          </span>
        )}
      </Button>
      <p className="text-xs text-center text-slate-400 flex items-center justify-center gap-1">
        <Lock className="h-3 w-3" />
        Secured by Stripe — Your card information is never stored on our servers
      </p>
    </form>
  );
}

// ── Inner page content ───────────────────────────────────────────────────────

function DepositPageContent({ token }: { token: string }) {
  const [bookingInfo, setBookingInfo] = useState<BookingInfo | null>(null);
  const [clientSecret, setClientSecret] = useState<string | null>(null);
  const [paymentIntentId, setPaymentIntentId] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  // Check for redirect-back success (3DS redirect case)
  useEffect(() => {
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search);
      if (params.get("confirmed") === "1") {
        const pi = params.get("pi");
        if (pi) {
          // Server-side confirm after 3DS redirect
          fetch("/api/payments/deposit/capture", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ token, payment_intent_id: pi }),
          }).then(() => setSuccess(true)).catch(console.error);
        }
      }
    }
  }, [token]);

  useEffect(() => {
    async function load() {
      try {
        // 1. Fetch booking info
        const infoRes = await fetch(`/api/payments/deposit?token=${encodeURIComponent(token)}`);
        if (!infoRes.ok) {
          const err = await infoRes.json().catch(() => ({ error: "Not found" }));
          setError((err as { error?: string }).error ?? "Invalid deposit link.");
          setLoading(false);
          return;
        }
        const info: BookingInfo = await infoRes.json();
        setBookingInfo(info);

        if (info.already_held || info.completed) {
          setSuccess(info.already_held ?? false);
          setLoading(false);
          return;
        }

        // Note: operator Stripe connection is enforced at deposit-link creation
        // (/api/payments/deposit/initiate). If a link exists without a connected
        // account, the charge falls back to the platform account server-side.

        // 2. Create / reuse PaymentIntent
        const piRes = await fetch("/api/payments/deposit", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ deposit_token: token }),
        });
        if (!piRes.ok) {
          const err = await piRes.json().catch(() => ({ error: "PI error" }));
          setError((err as { error?: string }).error ?? "Failed to initialize payment.");
          setLoading(false);
          return;
        }
        const piData = await piRes.json();
        setClientSecret(piData.client_secret);
        setPaymentIntentId(piData.payment_intent_id);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load deposit page.");
      } finally {
        setLoading(false);
      }
    }

    load();
  }, [token]);

  function formatDate(d: string) {
    return new Date(d + "T12:00:00Z").toLocaleDateString("en-US", {
      month: "short", day: "numeric", year: "numeric",
    });
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-[#F8F9FC]">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-[#2EBD6B] border-t-transparent" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-[#F8F9FC] p-4">
        <Card className="border-0 bg-white shadow-sm ring-0 max-w-md w-full">
          <CardContent className="flex flex-col items-center py-12 text-center gap-4">
            <div className="h-14 w-14 rounded-full bg-red-100 flex items-center justify-center">
              <AlertCircle className="h-7 w-7 text-red-600" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-1">Link Not Found</h2>
              <p className="text-slate-500 text-sm">{error}</p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (success || bookingInfo?.already_held) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-[#F8F9FC] p-4">
        <Card className="border-0 bg-white shadow-sm ring-0 max-w-md w-full">
          <CardContent className="flex flex-col items-center py-12 text-center gap-4">
            <div className="h-16 w-16 rounded-full bg-emerald-100 flex items-center justify-center">
              <CheckCircle2 className="h-8 w-8 text-emerald-600" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-2">Deposit Hold Authorized!</h2>
              <p className="text-slate-500 text-sm">
                Your security deposit of <strong>${Number(bookingInfo?.deposit_amount ?? 0).toFixed(2)}</strong> has been 
                authorized. This is a hold only — you will not be charged unless there is damage or late fees.
              </p>
            </div>
            <div className="rounded-lg bg-emerald-50 border border-emerald-200 p-4 w-full text-left text-sm text-emerald-700">
              <p className="font-semibold mb-1">What happens next?</p>
              <ul className="list-disc list-inside space-y-1 text-xs">
                <li>Return the vehicle in good condition → hold is released</li>
                <li>Hold expires automatically after 7 days if not captured</li>
                <li>You&apos;ll receive an email when the hold is released</li>
              </ul>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!bookingInfo) return null;

  const vehicleLabel = bookingInfo.vehicle
    ? `${bookingInfo.vehicle.year} ${bookingInfo.vehicle.make} ${bookingInfo.vehicle.model}`
    : "Rental Vehicle";

  return (
    <div className="min-h-screen bg-[#F8F9FC] py-8 px-4">
      {/* Header */}
      <div className="max-w-xl mx-auto mb-8 text-center">
        <div className="inline-flex items-center gap-2 bg-white rounded-full px-4 py-2 shadow-sm mb-4">
          <div className="h-6 w-6 rounded-full bg-[#2EBD6B] flex items-center justify-center">
            <ShieldCheck className="h-3.5 w-3.5 text-white" />
          </div>
          <span className="text-sm font-semibold text-slate-700">PCR Booking · Secure Deposit</span>
        </div>
        <h1 className="text-2xl font-bold text-slate-900 mb-1">Security Deposit Authorization</h1>
        <p className="text-slate-500 text-sm">
          {bookingInfo.operator_name} requires a deposit hold before your rental begins.
        </p>
      </div>

      <div className="max-w-xl mx-auto grid gap-6">
        {/* Booking summary */}
        <Card className="border-0 bg-white shadow-sm ring-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Booking Summary</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="flex items-center gap-3">
              <div className="h-9 w-9 rounded-lg bg-slate-100 flex items-center justify-center">
                <Car className="h-4 w-4 text-slate-500" />
              </div>
              <div>
                <p className="font-semibold text-slate-900">{vehicleLabel}</p>
                <p className="text-slate-400 text-xs">{bookingInfo.operator_name}</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3 pt-1">
              <div className="flex items-center gap-2">
                <Calendar className="h-3.5 w-3.5 text-slate-400" />
                <div>
                  <p className="text-xs text-slate-400">Pickup</p>
                  <p className="font-medium text-slate-700">{formatDate(bookingInfo.start_date)}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Calendar className="h-3.5 w-3.5 text-slate-400" />
                <div>
                  <p className="text-xs text-slate-400">Return</p>
                  <p className="font-medium text-slate-700">{formatDate(bookingInfo.end_date)}</p>
                </div>
              </div>
            </div>
            <div className="border-t pt-3 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-[#2EBD6B]" />
                <span className="font-semibold text-slate-700">Deposit Hold Amount</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xl font-bold text-slate-900">
                  ${Number(bookingInfo.deposit_amount).toFixed(2)}
                </span>
                <Badge className="bg-amber-50 text-amber-700 border-amber-200 text-xs">Hold Only</Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Payment form */}
        <Card className="border-0 bg-white shadow-sm ring-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <Lock className="h-4 w-4 text-[#2EBD6B]" />
              Card Authorization
            </CardTitle>
          </CardHeader>
          <CardContent>
            {clientSecret ? (
              <Elements
                stripe={stripePromise}
                options={{
                  clientSecret,
                  appearance: {
                    theme: "stripe",
                    variables: {
                      colorPrimary: "#2EBD6B",
                      borderRadius: "6px",
                    },
                  },
                }}
              >
                <DepositForm
                  token={token}
                  bookingInfo={bookingInfo}
                  paymentIntentId={paymentIntentId}
                  onSuccess={() => setSuccess(true)}
                />
              </Elements>
            ) : (
              <div className="flex items-center justify-center py-8">
                <div className="h-6 w-6 animate-spin rounded-full border-2 border-[#2EBD6B] border-t-transparent" />
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// ── Default export ───────────────────────────────────────────────────────────

export default function DepositPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = use(params);
  return (
    <Suspense
      fallback={
        <div className="flex items-center justify-center min-h-screen bg-[#F8F9FC]">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-[#2EBD6B] border-t-transparent" />
        </div>
      }
    >
      <DepositPageContent token={token} />
    </Suspense>
  );
}
