-- Expand subscriptions.status CHECK constraint to cover all Stripe subscription statuses.
-- Stripe can send: incomplete, incomplete_expired, trialing, active, past_due, canceled, unpaid, paused
-- Original constraint only allowed: active, canceled, past_due, trialing

-- Drop the auto-named inline constraint generated by the initial schema
ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS subscriptions_status_check;

-- Add expanded constraint with all valid Stripe statuses
ALTER TABLE subscriptions
  ADD CONSTRAINT subscriptions_status_check
  CHECK (status IN (
    'incomplete',
    'incomplete_expired',
    'trialing',
    'active',
    'past_due',
    'canceled',
    'unpaid',
    'paused'
  ));
